### ISSUE TITLE
Using load with nw.js >= 0.13 crashes with signal 11 SEGV_MAPERR

### ISSUE THREAD

**Issue by porsager** [3rd-Eden/load#4]
Hi.

I'm using primus in a lot of our nw.js apps, and while trying to upgrade them to nw.js >= 0.13 I've found that doing require('primus').createSocket() crashes nw with a V8 stack trace.

I traced it down to when load is being called, but I have a hard time figuring out what's going on.
The hard crash doesn't happen if i comment out line 46 in load/index.js, and I've tried selectively removing some of the globals from the context object that makes it break, but it seems to be more than just a few, so I might be looking at it the wrong way.

I hope you can make some sense of it.

Let me know if you think I should rather file this issue with nwjs instead.

Thanks for the great work.

**Comment by 3rd-Eden** [comment]
What is "nw.js"?

Arnout Kazemier

**Comment by lpinca** [comment]
@3rd-Eden node-webkit like electron.

**Comment by lpinca** [comment]
@porsager does it crash with `primus@5.2.1`?

**Comment by porsager** [comment]
Yeah i guess it's still known as Node-Webkit ;)

I tried with primus@5.2.2 and now also 5.2.1 which both crashes.

I also gave it a try with electron, and that also crashes if i try the same in the renderer process which would be the equivalent to node webkit. I guess it's happening due to the shared node/browser context, but it didn't happen with node-webkit pre 0.13 for example, so something changed, maybe due to a chromium / node version bump.

I'll dig a little deeper and see which globals that make it crash that way.

**Comment by lpinca** [comment]
I made you test `primus@5.2.1` for nothing as the issue should be [`here`](https://github.com/3rd-Eden/load/blob/96915d7b4de879eb60cc26f64b6bf0b40cf056aa/index.js#L91-L99).

**Comment by porsager** [comment]
Ok, so now I found out it was the location key in the mapped "missing" modules that made it do the hard crash.

If I include "location" together with module and require in the filter you linked it works. 

That brings up a new error though which says "Uncaught SecurityError: An attempt was made to break through the security policy of the user agent."

If i also include "window" that takes care of the Uncaught SecurityError, and it seems primus works in my project then, but I guess it might break elsewhere...

So changing line 92 to the following makes it work

```
return prop !== 'module' && prop !== 'require' && prop !== 'location' && prop !== 'window';
```

**Comment by lpinca** [comment]
We use `load` to build the client for Node.js so it shouldn't be a big issue. I mean those globals are browser globals.

**Comment by porsager** [comment]
Great.

I just tested another project of ours which needed further things excluded not to crash. In this case I also had to exclude "global" and "self".

Would you think it's possible to reverse the loading to take just what's required instead of taking everything from the globals?
I imagine doing it with explicit exclusion might just cause a similar issue in a later version of nwjs/electron.

**Comment by lpinca** [comment]
@porsager I was thinking the same, but I'm not sure what is required.

**Comment by lpinca** [comment]
I wonder if it makes sense to use `vm` directly in Primus so we have a little more freedom and 1 less dependency.

**Comment by porsager** [comment]
I've just tested all our projects where i only add the following. That seems to work fine.

```
['require', 'Error', 'setTimeout', 'clearTimeout']
```

It also seems to work without 'Error', but you might know better if it's needed.

**Comment by lpinca** [comment]
I think `process`, `Buffer`, `setImmediate`, `clearImmediate`, `setInterval`, `clearInterval` should also be included and probably more, plugins may use more globals.

**Comment by lpinca** [comment]
@porsager https://github.com/primus/primus/pull/470 should fix the issue but I'm not very happy with it.
Using this approach we have to maintain the list of globals manually updating it every time it changes in node.

I wonder if there is a way to make `load` only lists node globals when used in nw.js or electron.

**Comment by porsager** [comment]
Ah. Very nice! Thanks a lot @lpinca it works great :)
